#!/bin/bash

echo "🚀 Calendario AI - Setup Guida"
echo "================================"
echo ""
echo "1. Assicurati che Node.js 18+ sia installato:"
echo "   node --version"
echo ""
echo "2. Installa le dipendenze:"
echo "   npm install"
echo ""
echo "3. Copia il file .env:"
echo "   cp .env.example .env"
echo ""
echo "4. Configura i Provider AI in .env:"
echo ""
echo "   📘 Google Gemini:"
echo "   - Vai su https://ai.google.dev"
echo "   - Ottieni una chiave API gratuita"
echo "   - Aggiungi a .env: GEMINI_API_KEY=your_key"
echo ""
echo "   🔗 OpenRouter:"
echo "   - Registrati su https://openrouter.ai"
echo "   - Aggiungi a .env: OPENROUTER_API_KEY=your_key"
echo ""
echo "   🏠 Ollama (locale):"
echo "   - Installa da https://ollama.ai"
echo "   - Esegui: ollama pull mistral"
echo "   - Esegui: ollama serve"
echo "   - Aggiungi a .env: OLLAMA_MODEL=mistral"
echo ""
echo "5. Avvia i servizi (in 2 terminali diversi):"
echo ""
echo "   Terminal 1 (Backend):"
echo "   cd apps/api && npm run dev"
echo ""
echo "   Terminal 2 (Frontend):"
echo "   cd apps/web && npm run dev"
echo ""
echo "6. Apri http://localhost:5173 nel browser"
echo ""
echo "❓ Aiuto?"
echo "   - Leggi README.md per la documentazione completa"
echo "   - Controlla che le porte 3000 e 5173 siano libere"
echo "   - Verifica i log del server per errori"
echo ""
echo "✨ Buona organizzazione!"
