import { ProviderConfig, ProviderError } from '@calendario/domain';
import { AiProvider, ProviderSession, ProviderSessionOptions } from '../types';
import { CALENDAR_TOOLS, toOpenAITools } from '../tools';

export class OpenRouterProvider implements AiProvider {
  id = 'openrouter';
  label = 'OpenRouter';
  local = false;
  config: ProviderConfig;
  private apiKey: string | null = null;
  private baseUrl = 'https://openrouter.ai/api/v1';

  constructor(apiKey?: string) {
    this.config = {
      id: 'openrouter',
      type: 'openai-compatible',
      label: this.label,
      baseUrl: this.baseUrl,
      enabled: !!apiKey,
      apiKey,
    };
    this.apiKey = apiKey || null;
  }

  setApiKey(apiKey: string): void {
    this.apiKey = apiKey;
    this.config.apiKey = apiKey;
    this.config.enabled = true;
  }

  async isConfigured(): Promise<boolean> {
    return !!this.apiKey;
  }

  async isOnline(): Promise<boolean> {
    if (!this.apiKey) return false;

    try {
      const response = await fetch(`${this.baseUrl}/models`, {
        headers: { Authorization: `Bearer ${this.apiKey}` },
        signal: AbortSignal.timeout(5000),
      });
      return response.ok;
    } catch {
      return false;
    }
  }

  async resolveModel(preferred?: string): Promise<string> {
    // Default to a fast, affordable model
    return preferred || 'openrouter/auto';
  }

  async startSession(options: ProviderSessionOptions): Promise<ProviderSession> {
    if (!this.apiKey) {
      throw new ProviderError('OpenRouter API key not configured');
    }

    return new OpenRouterSession(this.apiKey, this.baseUrl, options);
  }

  async getStatus() {
    const configured = await this.isConfigured();
    const online = await this.isOnline();
    const model = await this.resolveModel();

    return {
      online,
      configured,
      model,
    };
  }
}

class OpenRouterSession implements ProviderSession {
  constructor(
    private apiKey: string,
    private baseUrl: string,
    private options: ProviderSessionOptions
  ) {}

  async complete(
    messages: Array<{ role: 'user' | 'assistant'; content: string }>,
    tools?: any
  ): Promise<{ content: string; toolCalls?: Array<{ name: string; input: Record<string, unknown> }> }> {
    const model = this.options.model || 'openrouter/auto';
    const systemPrompt = this.options.systemPrompt || 'You are a helpful calendar assistant.';
    const wantTools = tools === undefined || tools === true || (Array.isArray(tools) && tools.length > 0);

    try {
      const body: any = {
        model,
        messages: [
          { role: 'system', content: systemPrompt },
          ...messages,
        ],
        max_tokens: this.options.maxTokens || 2048,
        temperature: this.options.temperature ?? 0.2,
      };
      if (wantTools) body.tools = toOpenAITools();
      const response = await fetch(`${this.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
        signal: this.createAbortSignal(),
      });

      if (!response.ok) {
        throw new ProviderError(
          `OpenRouter API error: ${response.statusText}`,
          response.status === 429
        );
      }

      const data = (await response.json()) as any;

      if (!data.choices || !data.choices[0]) {
        throw new ProviderError('No content generated by OpenRouter');
      }

      const content = data.choices[0].message?.content || '';
      const toolCalls = parseOpenAIToolCalls(data.choices[0].message);
      return toolCalls.length > 0 ? { content, toolCalls } : { content };
    } catch (error) {
      if (error instanceof ProviderError) throw error;
      throw new ProviderError(`OpenRouter request failed: ${String(error)}`, true);
    }
  }

  async stream(
    messages: Array<{ role: 'user' | 'assistant'; content: string }>,
    tools?: any,
    onChunk?: (chunk: string) => void
  ): Promise<{ content: string; toolCalls?: Array<{ name: string; input: Record<string, unknown> }> }> {
    const model = this.options.model || 'openrouter/auto';
    const systemPrompt = this.options.systemPrompt || 'You are a helpful calendar assistant.';
    const wantTools = tools === undefined || tools === true || (Array.isArray(tools) && tools.length > 0);

    try {
      const body: any = {
        model,
        messages: [
          { role: 'system', content: systemPrompt },
          ...messages,
        ],
        max_tokens: this.options.maxTokens || 2048,
        temperature: this.options.temperature ?? 0.2,
        stream: true,
      };
      if (wantTools) body.tools = toOpenAITools();
      const response = await fetch(`${this.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
        signal: this.createAbortSignal(),
      });

      if (!response.ok) {
        throw new ProviderError(`OpenRouter API error: ${response.statusText}`);
      }

      let fullContent = '';
      const toolDeltas: Record<number, { name: string; args: string }> = {};

      if (response.body) {
        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = '';

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split('\n');
          buffer = lines.pop() || '';

          for (const line of lines) {
            if (line.startsWith('data: ')) {
              const data = line.slice(6);
              if (data === '[DONE]') continue;

              try {
                const parsed = JSON.parse(data);
                const delta = parsed.choices?.[0]?.delta;
                if (typeof delta?.content === 'string' && delta.content) {
                  fullContent += delta.content;
                  onChunk?.(delta.content);
                }
                // Accumula tool_calls streammati (formato OpenAI)
                const tcs = delta?.tool_calls || [];
                for (const tc of tcs) {
                  const idx = Number(tc.index ?? 0);
                  toolDeltas[idx] = toolDeltas[idx] || { name: '', args: '' };
                  if (tc.function?.name) toolDeltas[idx].name += tc.function.name;
                  if (typeof tc.function?.arguments === 'string') toolDeltas[idx].args += tc.function.arguments;
                }
              } catch {
                // Ignore parse errors
              }
            }
          }
        }
      }

      const toolCalls = Object.values(toolDeltas).flatMap((t) => {
        if (!t.name || !(CALENDAR_TOOLS as Record<string, any>)[t.name]) return [];
        let input: Record<string, unknown> = {};
        try { input = t.args ? JSON.parse(t.args) : {}; } catch { input = {}; }
        return [{ name: t.name, input }];
      });
      if (toolCalls.length > 0) return { content: fullContent, toolCalls };
      return { content: fullContent };
    } catch (error) {
      if (error instanceof ProviderError) throw error;
      throw new ProviderError(`OpenRouter stream failed: ${String(error)}`, true);
    }
  }

  async close(): Promise<void> {
    // Cleanup if needed
  }

  private createAbortSignal(): AbortSignal | undefined {
    if (!this.options.timeout) return undefined;
    const controller = new AbortController();
    setTimeout(() => controller.abort(), this.options.timeout);
    return controller.signal;
  }
}

/** Parsing risposta OpenAI chat/completions: tool_calls nativi + whitelist tool calendario. */
function parseOpenAIToolCalls(message: any): Array<{ name: string; input: Record<string, unknown> }> {
  const valid = new Set(Object.keys(CALENDAR_TOOLS));
  const raw = message?.tool_calls || message?.toolCalls || [];
  const out: Array<{ name: string; input: Record<string, unknown> }> = [];
  for (const t of raw) {
    const name = t?.function?.name || t?.name;
    if (!name || !valid.has(name)) continue;
    let input = t?.function?.arguments ?? t?.input ?? {};
    if (typeof input === 'string') {
      try { input = JSON.parse(input); } catch { input = {}; }
    }
    out.push({ name, input: (input || {}) as Record<string, unknown> });
  }
  return out;
}
